### ISSUE TITLE
Broken link in Pypi.org documentation

### ISSUE THREAD

**Issue by seanspicer** [Reveal-Energy-Services/orchid-python-api#1]
This link on pypi.org is broken:

![image](https://user-images.githubusercontent.com/11943280/90258059-a016a080-de0d-11ea-96f1-80468babba3e.png)

**Comment by mrwizard82d1** [comment]
Oops. When I wrote the original `READM`E, I assumed my target audience was Reveal Developers. When we changed to targeting others, I moved some of the development details into a separate directory. When I packaged the code for publishing, I specifically *excluded* the `dev-docs` directory because, "Only developers care about it."

I think an easy fix. We just need to prioritize.

**Comment by mrwizard82d1** [comment]
Repaired in release 2020.4.232
