### ISSUE TITLE
Creating a monitor plot displays a `numpy` warning about a deprecated function

### ISSUE THREAD

**Issue by mrwizard82d1** [Reveal-Energy-Services/orchid-python-api#13]
Given I have run `jupyter lab`
When I run the `plot_monitor_curves` notebook
Then I see the deprecation warning
   """
   c:\users\larry.jones\appdata\local\pypoetry\cache\virtualenvs\orchid-python-api-_tsnd6qt-py3.8\lib\site- 
   packages\numpy\core\_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which 
   is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you  
   must specify 'dtype=object' when creating the ndarray 
   return array(a, dtype, copy=False, order=order)
   """

**Comment by mrwizard82d1** [comment]
Without looking in detail, I believe this warning occurs in code that we call, perhaps in the `pandas` package.

However, we still need to look at this warning.

**Comment by dlerohl** [comment]
Numpy now requires a dtype to be specified as 'object' when dealing with "ragged nested sequences" in np.array(). Here, however it was invoked when calling the `np.reshape()` function on the list of pd.Series objects. 
The fix was to create cast the list of pd.Series to a `np.array(list_reference, dtype='object')` prior to the np.reshape() function call.
